version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*" # All dependabot updates are grouped
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates to Python packages every week
      interval: "weekly"
    groups:
      pip-dependencies:
        patterns:
          - "*" # All dependabot updates are grouped
